### PR TITLE
Add system requirements specification.

### PR DESCRIPTION
**Pull request by gevorgyana**
Signed-off-by: Artyom Gevorgyan <artemhevorhian@gmail.com>

### CODE REVIEW

**Review by Pilipets — CHANGES_REQUESTED** [review]
Could you add a version of the report that is editable?

**Comment by gevorgyana** [comment]
> Could you add a version of the report that is editable?

what do you mean?

**Comment by Pilipets** [comment]
> > Could you add a version of the report that is editable?
> 
> what do you mean?

If you check the utils folder, we have versions of the reports that can be modified on the request.

**Comment by gevorgyana** [comment]
> > > Could you add a version of the report that is editable?
> > 
> > 
> > what do you mean?
> 
> If you check the utils folder, we have versions of the reports that can be modified on the request.

So you mean .docx.

**Review by Pilipets — APPROVED** [review]

**Comment by Pilipets** [comment]
Approved, though I still suggest adding a meaningful filename - for example, ProjectRequirements

**Comment by gevorgyana** [comment]
> Approved, though I still suggest adding a meaningful filename - for example, ProjectRequirements

SRS is a common name, means system requirements specification.

**Pull request merged**
