### PR TITLE
Use Github Issues exclusively.

### PR DESCRIPTION
**Pull request by gevorgyana**
Github issues are used for bug/task-tracking.

Signed-off-by: Artyom Gevorgyan <artemhevorhian@gmail.com>

### CODE REVIEW

**Comment by Pilipets** [comment]
Looks okay, but, please, add a meaningful commit message when merging this - something like "Removed do_research.md in favor of using GitHub issues for bug/task-tracking"

**Review by Pilipets — CHANGES_REQUESTED** [review]
Please, check the comment in the PR.

**Comment by gevorgyana** [comment]
https://www.midori-global.com/blog/2018/04/02/git-50-72-rule
Suggest that we use 50/72 best practice for naming commits. 
"Removed do_research.md in favor of using GitHub issues for bug/task-tracking" is too long for header.

**Comment by Pilipets** [comment]
> https://www.midori-global.com/blog/2018/04/02/git-50-72-rule
> Suggest that we use 50/72 best practice for naming commits.
> "Removed do_research.md in favor of using GitHub issues for bug/task-tracking" is too long for the header.

I agree with that - didn't say it must be a header.
The header can be "Started using Github Issues exclusively".
Description - "Removed do_research.md in favor of using GitHub issues for bug/task-tracking".

**Review by Pilipets — APPROVED** [review]
Please, check the comment in the PR.

**Pull request merged**
